import { FormEvent, useEffect, useMemo, useState } from 'react'
import { User, createUserWithEmailAndPassword, onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'firebase/auth'
import { doc, getDoc, onSnapshot, serverTimestamp, setDoc } from 'firebase/firestore'
import { addMonths, eachDayOfInterval, endOfMonth, format, getDay, parseISO, startOfMonth, subMonths } from 'date-fns'
import { es } from 'date-fns/locale'
import { auth, db, firebaseConfigured } from './services/firebase'
import { ResidencyYear, salaryRates } from './config/salaryRates'
import { getHolidays } from './config/holidays'
import { calculateSalary } from './domain/calculateSalary'

type Profile={residencyYear:ResidencyYear;baseSalary:number;irpf:number;specialHolidays:string[]}
const initial:Profile={residencyYear:'R1',baseSalary:0,irpf:0,specialHolidays:[]}
const euro=new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'})

function Login(){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[create,setCreate]=useState(false);const[error,setError]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');try{if(!auth)return;await(create?createUserWithEmailAndPassword(auth,email,password):signInWithEmailAndPassword(auth,email,password))}catch(err){setError(err instanceof Error?err.message:'No se pudo acceder')}}
 return <main className="center"><form className="card login" onSubmit={submit}><div className="brand">G</div><h1>Guardias médicas</h1><p>Calcula tu salario esperado, sin complicaciones.</p><label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input type="password" autoComplete={create?'new-password':'current-password'} minLength={6} required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary">{create?'Crear cuenta':'Entrar'}</button><button type="button" className="link" onClick={()=>setCreate(!create)}>{create?'Ya tengo una cuenta':'Crear cuenta'}</button></form></main>}

function Settings({profile,onSave,onClose}: {profile:Profile;onSave:(p:Profile)=>void;onClose:()=>void}){const[p,setP]=useState(profile);const[newDate,setNewDate]=useState('');
 const add=()=>{if(newDate&&!p.specialHolidays.includes(newDate)){setP({...p,specialHolidays:[...p.specialHolidays,newDate].sort()});setNewDate('')}}
 return <div className="overlay"><section className="modal"><header><h2>Ajustes</h2><button className="icon" onClick={onClose} aria-label="Cerrar">×</button></header><label>Año de residencia<select value={p.residencyYear} onChange={e=>{const y=e.target.value as ResidencyYear;setP({...p,residencyYear:y})}}>{Object.keys(salaryRates).map(y=><option key={y}>{y}</option>)}</select></label><small>Sugerencia de nómina ordinaria: {euro.format(salaryRates[p.residencyYear].base)}</small><label>Salario base bruto mensual (€)<input type="number" min="0" step="0.01" value={p.baseSalary||''} placeholder={String(salaryRates[p.residencyYear].base)} onChange={e=>setP({...p,baseSalary:Number(e.target.value)})}/></label><label>IRPF (%)<input type="number" min="0" max="100" step="0.1" value={p.irpf||''} onChange={e=>setP({...p,irpf:Number(e.target.value)})}/></label><details><summary>Festivos especiales</summary><p className="muted">Añade solo fechas confirmadas por tu centro.</p><div className="date-add"><input type="date" value={newDate} onChange={e=>setNewDate(e.target.value)}/><button type="button" onClick={add}>Añadir</button></div>{p.specialHolidays.map(d=><div className="special" key={d}><span>{d}</span><button onClick={()=>setP({...p,specialHolidays:p.specialHolidays.filter(x=>x!==d)})}>Quitar</button></div>)}</details><button className="primary" onClick={()=>onSave(p)}>Guardar ajustes</button></section></div>}

function Dashboard({user}:{user:User}){const[month,setMonth]=useState(new Date(2026,8,1));const[profile,setProfile]=useState<Profile|null>(null);const[guards,setGuards]=useState<string[]>([]);const[settings,setSettings]=useState(false);const[loading,setLoading]=useState(true);const key=format(month,'yyyy-MM');
 useEffect(()=>{if(!db)return;getDoc(doc(db,'users',user.uid,'profile')).then(s=>{setProfile(s.exists()?s.data() as Profile:initial);setLoading(false)})},[user.uid])
 useEffect(()=>{if(!db)return;return onSnapshot(doc(db,'users',user.uid,'months',key),s=>setGuards(s.exists()?(s.data().guards??[]):[]))},[user.uid,key])
 const calc=useMemo(()=>calculateSalary({guards,residencyYear:profile?.residencyYear??'R1',baseSalary:profile?.baseSalary??0,irpf:profile?.irpf??0,specialHolidays:profile?.specialHolidays??[]}),[guards,profile])
 const days=eachDayOfInterval({start:startOfMonth(month),end:endOfMonth(month)});const blanks=(getDay(startOfMonth(month))+6)%7;const holidays=getHolidays(month.getFullYear())
 const toggle=async(date:string)=>{if(!db)return;const next=guards.includes(date)?guards.filter(x=>x!==date):[...guards,date].sort();setGuards(next);await setDoc(doc(db,'users',user.uid,'months',key),{guards:next,updatedAt:serverTimestamp()},{merge:true})}
 const save=async(p:Profile)=>{if(!db)return;await setDoc(doc(db,'users',user.uid,'profile'),{...p,updatedAt:serverTimestamp(),createdAt:serverTimestamp()},{merge:true});setProfile(p);setSettings(false)}
 if(loading||!profile)return <main className="center"><p>Cargando…</p></main>
 return <main className="app"><header className="top"><button className="text-button" onClick={()=>auth&&signOut(auth)}>Salir</button><button className="text-button" onClick={()=>setSettings(true)}>Ajustes</button></header><section className="hero"><div className="month-nav"><button onClick={()=>setMonth(subMonths(month,1))} aria-label="Mes anterior">‹</button><h1>{format(month,'MMMM yyyy',{locale:es})}</h1><button onClick={()=>setMonth(addMonths(month,1))} aria-label="Mes siguiente">›</button></div><p>Salario esperado</p><strong>{euro.format(calc.estimatedAfterIrpf)}</strong><span>Neto estimado tras IRPF</span><div className="summary"><span>Base <b>{euro.format(calc.baseSalary)}</b></span><span>Guardias <b>{euro.format(calc.guardPayments)}</b></span><span>IRPF estimado <b>−{euro.format(calc.irpfAmount)}</b></span></div></section><section className="calendar-card"><h2>Marca los días en los que tienes guardia</h2><div className="weekdays">{'LMXJVSD'.split('').map((d,i)=><span key={i}>{d}</span>)}</div><div className="grid">{Array.from({length:blanks},(_,i)=><span key={'b'+i}/>)}{days.map(day=>{const date=format(day,'yyyy-MM-dd');const selected=guards.includes(date);const holiday=Boolean(holidays[date]);const special=profile.specialHolidays.includes(date);return <button key={date} onClick={()=>toggle(date)} className={`day ${selected?'selected':''} ${holiday||special?'holiday':''}`} aria-pressed={selected} title={special?'Festivo especial':holidays[date]}><span>{format(day,'d')}</span>{selected&&<b>G</b>}{(holiday||special)&&<i/>}</button>})}</div></section><details className="breakdown"><summary>Ver desglose ({guards.length})</summary>{calc.details.length===0?<p className="muted">Aún no hay guardias marcadas.</p>:calc.details.map(item=><div key={item.date}><span>{format(parseISO(item.date),'d MMMM',{locale:es})} — {item.label}</span><b>{euro.format(item.amount)}</b></div>)}<footer>Total guardias <b>{euro.format(calc.guardPayments)}</b></footer></details><p className="disclaimer">Estimación orientativa. No incluye otras cotizaciones o retenciones.</p>{settings&&<Settings profile={profile} onSave={save} onClose={()=>setSettings(false)}/>}</main>}

export function App(){const[user,setUser]=useState<User|null>(null);const[ready,setReady]=useState(false);useEffect(()=>{if(!auth){setReady(true);return}return onAuthStateChanged(auth,u=>{setUser(u);setReady(true)})},[]);if(!firebaseConfigured)return <main className="center"><section className="card config"><h1>Configura Firebase</h1><p>Faltan las credenciales de Firebase. Copia <code>.env.example</code> a <code>.env</code>, completa sus seis variables y reinicia la aplicación.</p></section></main>;if(!ready)return <main className="center">Cargando…</main>;return user?<Dashboard user={user}/>:<Login/>}
